### ISSUE TITLE
`Result::unwrap()` on an `Err` value: OddLength

### ISSUE THREAD

**Issue by bemxio** [uhwot/lbp_archive_dl#3]
When trying to run the project compiled from the `main` branch with the command below, I get the following error:
```sh
.../LBP/Levels $ RUST_BACKTRACE=1 ~/archive_dl "GALACTIC LB Soccer FOOTBALL.bin" "GALACTIC LB Soccer FOOTBALL"
thread 'main' panicked at src/main.rs:175:49:
called `Result::unwrap()` on an `Err` value: OddLength
```

I am using Termux (sadly cannot use a PC at the moment, so I gotta torture myself with it), with `rustc` and `cargo` at version 1.78.0.

**Comment by uhwot** [comment]
you're using it wrong lol
first argument is the rootLevel hash, if you're using [this site](https://maticzpl.xyz/lbpfind/) copypaste this :)
![image](https://github.com/uhwot/lbp_archive_dl/assets/54753080/bc9b4d60-a5f0-48ff-a35a-41661d2b4d74)

**Comment by bemxio** [comment]
Oh I see, thought the script wants to read the file directly. Thanks!
